[feat] 온보딩 / 카카오 로그인 구현
team-winey/Winey-AOS pull request #103
Opened 2023-08-07 02:56 UTC by Sangwook123

- closed #97

## 📝 Work Description

 카카오 로그인 구현
 로그인 API 구현
 토큰 재발급 자동화
 자동로그인
 데이터스토어 유저정보 저장

## 📸 Screenshot

## 📣 To Reviewers

내일까지 작성해주시면 감사하겠습니다 !!
위니피드 변경사항 있습니다 ! 팝업메뉴 띄울때 기존 AuthInterceptor의 USER_ID를 가져와서 비교하는 것에서 데이터스토어에 저장된 userId를 비교하는 것으로 변경했습니다 ! 혜선이 참고해주세요 ~

토큰 재발급의 경우 아직 만료된 토큰으로 시험해본적 없어서 기능이 제대로 동작하는지 확인 해봐야할것같습니다 !

2023-08-07 15:06 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
> +        if (accessToken.isNullOrEmpty() || accessToken == "") {
isNullOrBlank 함수만 사용해도 될 거 같아요! 

- [[내 맘대로 정리한 Kotlin] isEmpty와 isBlank의 차이점](https://holika.tistory.com/entry/%EB%82%B4-%EB%A7%98%EB%8C%80%EB%A1%9C-%EC%A0%95%EB%A6%AC%ED%95%9C-Kotlin-isEmpty%EC%99%80-isBlank%EC%9D%98-%EC%B0%A8%EC%9D%B4%EC%A0%90)
- https://devbearkinf.tistory.com/46

2023-08-07 15:08 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/splash/SplashActivity.kt
> +            checkAccessTokenAndNavigate()
checkAutoLogin 이라는 함수명은 어떨까요?

2023-08-07 15:11 UTC, leeeha requested changes
코드량이 엄청 많네!! 진짜 고생많았어 👍👍👍 나도 리뷰하는데 3시간 좀 넘은 거 같아ㅋㅋㅋ

코루틴 Dispatcher 지정하는 코드에 대해서는 나도 더 공부해보고 리뷰 다시 달게!

2023-08-07 20:30 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
> +                        .build()
저희 명세서에는 accessToken이 만료되어 refreshToken을 재발급 받을때 request header에 refreshToken만 들어가있어서 해당 부분만 추가해 주었습니다 !

2023-08-07 21:05 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
> +                        .build()
suspend로 선언된 일시중단 함수는 코루틴 블럭내부에서 실행되어야하는데, getRefreshToken()이 suspend 함수라서 runblocking{}을 사용해야지 실행시킬 수 있었습니다 ! intercept 자체를 suspend함수로 변경하는게 가장 좋은 방법일거라 생각되지만 Okhttp 인터셉터에서 suspend 함수를 직접 호출하는 지원되지 않는다고 하네요 ㅜ ㅜ 좀 더 나은 방법이 있을까요?

2023-08-07 21:07 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
> +        private const val VALID_TOKEN = 200
넵 ㅎㅎ VALID_TOKEN은 이전에 썼던 코드에서 분기처리를 해주느라 사용했는데 지우는걸 깜빡잊었네요 수정하겠습니다

2023-08-07 21:08 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
> +        }
수정 하겠습니다!

2023-08-07 21:15 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/di/ServiceModule.kt
> +            }
일단 처음에 작성할때 카카오 플랫폼 안에서 앱과 사용자 카카오계정의 연결 상태를 해제하는 api라고 해서 회원탈퇴로 이해하고 작성해놓긴 했습니다만, 추후 해당 api 구현을 자세히 할 때 다시 확인해볼 생각입니다 !

2023-08-07 21:19 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/service/KakaoLoginService.kt
> +    fun kakaoDeleteAccount(kakaoLogoutCallBack: (Throwable?) -> Unit)
UserApiClient의 함수들은 기본적으로 비동기적 함수가 아니라고 해서 비동기 처리 해주지 않았습니다 ! 이와 관련되서 조금 더 알아보겠습니다 !

2023-08-07 21:21 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
> +        }
SOCIAL_ACCESS_TOKEN은 카카오로그인 api에서 전달받는 액세스 토큰이고 ACCESS_TOKEN은 SOCIAL_ACCESS_TOKEN으로 우리 서버의 로그인 api 실행 시 받는 서버전용 토큰입니다. 로그인 api를 제외한 우리 서버의 api 실행시 필요한 토큰은 ACCESS_TOKEN입니다 !

2023-08-07 21:22 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
> +        }
이런 편리한 방법이 .. 감사합니다 !

2023-08-07 21:23 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
> +    }
넵 ! !

2023-08-07 21:33 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
>      }
onResume에 getUser()를 실행시켰던 이유가 목표설정 바텀시트가 dismiss()할때 getUser()를 실행시키고 마이페이지에서는 onViewCreate에서만 실행시키는 것이 효율적일것 같아서 이처럼 해봤지만 livedata와 observer를 사용할때는 onStop일 경우 livedata의 변화를 감지하지 못해 뷰에 반영되지 않았었습니다. 그래서 onStop이 끝나고 onResume이 실행될때 뷰에 변경사항을 전달하기 위해서였는데, 이번에 stateflow로 리팩토링 후 다시 이전 방법처럼 고쳤더니 제대로 뷰에 반영이 됨을 확인하였습니다 ! 그래서 onResume에서 getUser를 실행시키면 불필요하게 여러번 getUser를 실행시키는 일이 생겼었는데, 이를 방지하기 위해 고쳐주었습니다 !

2023-08-07 21:43 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/OnBoardingActivity.kt
> +        lifecycleScope.launch {
잘 읽어보고 맞게 수정하겠습니다 감사합니다  ! !

2023-08-07 21:51 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/OnBoardingViewModel.kt
> +    }
사실 강의에서 여러 Dispatcher종류들 중에서 Dispatcher.IO가 데이터를 처리를할때 주로 쓰인다고 하는걸 따라서 써본건데, 저도 좀 더 공부해보고 다시 제대로 사용해봐야겠습니다 !

2023-08-08 05:21 UTC, sxunea requested changes
datastore 랑 hilt 같이 적용하느라 고생많았습니다 👍

2023-08-08 05:21 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/data/repository/AuthRepositoryImpl.kt
>          runCatching {
여기도 !! 연산자 사용하지 않게 바꿔주면 좋을거같습니다

2023-08-08 05:21 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
> +        }
오 나도 이거 알아갑니다 👍

2023-08-08 05:44 UTC, leeeha requested changes
리뷰 다 확인하느라 고생해따 😜 어려운 부분 맡았는데 넘 잘해주고 있어!! 좀만 더 화이팅!!

2023-08-08 05:44 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
> +                        .build()
저도 더 나은 방식을 고민해봤는데 DataStoreRepository 인터페이스 안에 변수들을 정의하고, 그걸 DataStoreRepositoryImpl 클래스에서 get, set 함수로 구현하는 건 어떨까요?? 

- Domain Layer: [DataStoreRepository](https://github.com/team-yello/YELLO-Android/blob/f32edb38e47b854ad6a06fd2b5272d73a8ed646f/domain/src/main/java/com/example/domain/YelloDataStore.kt)
- Data Layer : [DataStoreRepositoryImpl](https://github.com/team-yello/YELLO-Android/blob/f32edb38e47b854ad6a06fd2b5272d73a8ed646f/data/src/main/java/com/example/data/local/YelloDataStoreImpl.kt)

그러면 AuthInterceptor 에서 해당 변수들을 get, set 함수 사용하지 않고 편하게 가져올 수 있을 거 같아요! 

- [AuthInterceptor](https://github.com/team-yello/YELLO-Android/blob/f32edb38e47b854ad6a06fd2b5272d73a8ed646f/data/src/main/java/com/example/data/remote/interceptor/AuthInterceptor.kt)

옐로 코드에서 아이디어를 얻었습니다!

2023-08-08 05:44 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/data/repository/DataStoreRepositoryImpl.kt
> +        }
자세한 설명 감사합니다 :> 바로 이해 됐어요!!

2023-08-08 05:44 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/OnBoardingViewModel.kt
> +    }
"KAKAO" 상수화 시켜주세요 >.~

2023-08-08 05:44 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
> +        @Header("Authorization") accessToken: String,
postLogin API 보니까 socialAccessToken을 넣는 자리네요! 서버 액세스 토큰이랑 이름 헷갈리니까 socialAccessToken 으로 이름 짓는 게 어떨까요~~?

2023-08-08 05:44 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
> +        @Header("refreshToken") refreshToken: String
AuthInterceptor에서 refreshToken을 헤더에 넣어줬는데, 여기서 또 인자로 넣어줘야 하나용??

2023-08-08 05:44 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +        if (wineyFeed.userId == runBlocking { dataStoreRepository.getUserId().first() }) {
dataStoreRepository 자체에 데이터스토어에 저장한 변수들을 정의해놓으면 get을 더 편하게 할 수 있을 거 같아요!

2023-08-08 05:44 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
> +                        .build()
앗! 근데 저희는 옐로 코드와 다르게 get, set 할 때 모두 코루틴 suspend, Flow 사용해서 비동기 처리를 하니까 
변수들을 정의해준다 해도 get, set 할 때 코루틴 블록 내에서 처리를 해야 될 거 같네요..! 혜선이가 남긴 리뷰 참고하는 게 좋을 거 같아용

2023-08-08 06:13 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/data/interceptor/AuthInterceptor.kt
> +        this.newBuilder().addHeader(HEADER_TOKEN, runBlocking { getAccessToken() })
다들 [이 글](https://onlyfor-me-blog.tistory.com/519) 참고하면 좋을 거 같아요!!

runBlocking과 join 모두 동기적으로 처리하는 건데, 사실 DataStore의 가장 큰 장점은 코루틴과 flow 이용해서 "비동기적"이고 일관된 트랜잭션 방식으로 데이터를 저장하는 거라 생각해요! 

>DataStore는 기본 설정 또는 응용 프로그램 상태 같은 소량의 데이터를 안전하고 일관되게 저장하는 방법을 제공하는 제트팩 데이터 저장소 라이브러리다. **비동기** 데이터 저장을 가능하게 하는 **코루틴과 Flow를 기반**으로 한다. **쓰레드 세이프하고 차단되지 않기 때문에 쉐어드를 대체하는 걸 목표로 한다.** 2가지 다른 구현을 제공한다. 유형이 지정된 객체(프로토콜 버퍼 지원)를 저장하는 Proto DataStore,  키밸류 쌍을 저장하는 Preferences DataStore 다. 
앱에서 쉐어드를 쓰면서 재현하기 어려운 쉐어드 관련 문제를 경험했을 수 있다. 포착되지 않은 예외(uncaught exceptions)로 인해 분석에서 이상한 충돌이 발생하거나, **호출할 때 UI 쓰레드를 차단**하거나, 앱 전체에서 일관되지 않고 지속되는 데이터가 발생한다. DataStore는 이런 모든 문제를 해결하기 위해 구축됐다. 아래는 쉐어드와 DataStore 간의 직접적인 비교다

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/e0af1b0e-057e-4d1b-928f-fd42f838a92f)

>대부분의 데이터 저장소 API를 쓰면 **데이터가 수정될 때 비동기식으로 알림을 받아야 하는 경우가 많다.** 쉐어드는 일부 비동기 지원을 제공하지만 OnSharedPreferenceChangeListener를 통해 변경된 값에 대한 업데이트를 가져오는 경우에만 제공된다. 그러나 이 콜백은 메인 쓰레드에서 호출된다. 마찬가지로 파일 저장 작업을 백그라운드로 오프로드하려면 SharedPreferences.apply()를 쓸 수 있지만, 이렇게 하면 **fsync()의 UI 쓰레드가 차단돼 잠재적으로 버벅거림 및 ANR을 유발**할 수 있다. 이는 서비스가 시작 or 중지되거나 액티비티가 일시 중지(pauses) 또는 중지(stops)될 때마다 발생할 수 있다.
이에 비해 **DataStore는 코루틴과 Flow의 기능을 사용해서 데이터 검색 및 저장을 위한 완전 비동기식 API를 제공해 UI 쓰레드를 차단할 위협을 줄인다.** Flow에 익숙하지 않은 사람들에겐 비동기식으로 계산 가능한 값의 흐름일 뿐이다...(중략)

위의 설명들을 읽어보면 DataStore의 막강함은 완전한 비동기식 API 라는 점인 거 같아요! 

shared pref 는 결국 로컬 파일에 간단한 데이터 (ex. key-value 또는 객체) 를 저장하는 건데, 이 과정에서 위에 설명한 문제들이 발생해서 DataStore라는 Jetpack 라이브러리가 등장한 거 같아요! 

따라서, runBlocking, join 모두 사용하지 않고 코루틴 블록 내에서 비동기 처리하는 게 가장 좋다고 생각합니다!

2023-08-09 03:15 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/data/service/AuthService.kt
> +        @Header("refreshToken") refreshToken: String
AuthInterceptor에서는 토큰이 만료되었을 경우에만 refreshToken을 헤더에 넣어서 재발급을 받는 로직이라면, 지금 이 함수는 access토큰이 만료되지 않았어도 재발급을 받을 수 있도록 선언했습니다 ! 나중에 혹시 쓰일 수도 있을것 같아서 작성해두었는데, 나중에 쓰일 일 없을 것 같으면 지우겠습니다 !!

2023-08-09 07:01 UTC, merged