[feat] 온보딩 / 닉네임 뷰 구현, 서버통신
team-winey/Winey-AOS pull request #107
Opened 2023-08-10 09:00 UTC by leeeha

- closed #101 
- closed #102 

## 📝 Work Description

- 닉네임 뷰 구현 
- 닉네임 중복체크 서버 통신

## 📣 To Reviewers

- 오늘 자정까지 리뷰 부탁드려요!
- 현재 로그아웃이 구현되어 있지 않아서, 한번 로그인 하면 항상 자동로그인 되어 스플래쉬에서 메인 피드로 연결됩니다. 
- 닉네임 기능 테스트를 위해, 임시적으로 스플래쉬에서 자동로그인 함수를 실행하지 않고 바로 닉네임 액티비티로 넘어가도록 코드를 수정했어요. 본인이 개발하면서 필요한대로 화면 조정하다가 모든 기능 구현되면, 유저 플로우대로 화면 연결하겠습니다!

2023-08-10 11:39 UTC, Sangwook123 approved these changes
하은 폼 미쳤따! 고생했어 !!!!

2023-08-10 11:39 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
> +    }
inline fun 👍👍 한가지 궁금한 점이 있는데, 그럼 함수내부에서 다른 함수를 호출하는 함수들은 모두 inline을 사용해주는게 효율적인 것인지 궁금합니다 !

2023-08-10 11:39 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +        }
그럼 유저가 중복체크를하고, 한 글자를 썼다가 다시 지우는 경우에도 중복체크를 다시 해줘야하나요 ?

2023-08-10 11:39 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/util/binding/BindingAdapter.kt
> +}
와우 inputUiState 만들어서 input값 감지해서 데이터바인딩 해주니까 코드량도 줄고 가독성도 최곱니다 ! 마 이게 우리 리드다👏👏👏

2023-08-10 13:20 UTC, sxunea requested changes
xml 데이터바인딩 쪽 열심히 보고 갑니다 수고했어용 💯

2023-08-10 13:20 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameActivity.kt
> +            binding.etNickname.clearFocus()
포커스 처리까지 꼼꼼했다 👍

2023-08-10 13:20 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +            started = SharingStarted.WhileSubscribed(PRODUCE_STOP_TIMEOUT)
SharedFlow는 아직 써본적이 없는데 SharingStarted가 어떠한 역할을 하는지 궁금해요 ! 어떤 면에서 장점이 있는지도 알고싶습니다 ㅎㅎㅎ

2023-08-10 13:20 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +    val isClickedCheckBtn: StateFlow<Boolean> = _isClickedCheckBtn.asStateFlow()
중복체크 버튼이 체크되었는지 확인하는 state인것 같은데 이름을 isCheckBtnClicked로 하는건 어떨까요? 동사가 뒤로 가야 boolean 타입 state를 더 잘 명시할 수 있을것 같다는 생각입니다

2023-08-11 06:15 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/login/LoginActivity.kt
> +    }
[이 글](https://sabarada.tistory.com/176) 읽어보면 좋을 거 같아요! 

- 기본적으로 JVM의 JIT 컴파일러에 의해서 일반 함수들은 inline 함수를 사용했을 때 성능상 더 좋다고 판단되면, JVM이 자동으로 만들어준다고 합니다. 
- 인라인 함수가 여러 번 호출될 경우, 그 내용이 반복적으로 복사되어 한 함수에 들어가는 코드량이 많아질 수 있으므로 주의해야 합니다! 
- 일부 람다식 함수를 인라인 되지 않게 하게 하려면 아래처럼 `noinline` 키워드를 붙인다고 해요. 

```kotlin
inline fun shortFunc(a: Int, noinline out: (Int) -> Unit){
    println("Hello")
    out(a) // noinline
}

fun main() {
    shortFunc(3) { println("a: $it") }
}
```

cf) JIT 컴파일러란?
- https://catch-me-java.tistory.com/11
- https://hyeinisfree.tistory.com/26

2023-08-11 06:23 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +        }
현재 로직은 그렇습니닷,,, 

서버통신 완료된 `닉네임`과 해당 닉네임의 `중복여부`를 별도의 저장소에 따로 캐싱해두고, 해당 닉네임이 다시 입력될 경우 서버 통신 없이 UI에 결과를 바로 보여주는 게 성능상 더 좋을 거 같네요! 

그렇게 코드를 변경해보겠습니다!

2023-08-11 06:25 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +    val isClickedCheckBtn: StateFlow<Boolean> = _isClickedCheckBtn.asStateFlow()
오옹 그게 훨씬 가독성이 좋네요!! 네이밍 추천 감사함당💘

2023-08-11 10:12 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +            started = SharingStarted.WhileSubscribed(PRODUCE_STOP_TIMEOUT)
여기서 `stateIn` 함수는 map에서 반환 받은 Flow를 StateFlow 타입으로 변환하기 위해 사용했습니다! 

stateIn() 함수 인자로는 initialValue, scope, started 가 있는데 각각 요구하는 값은 아래와 같습니다.

- initialValue : StateFlow 의 초기 값
- scope : (여러 collector 간의 flow) 공유가 시작되는 Coroutine Scope
- started : 공유가 시작 및 중지되는 시기를 제어하기 위한 파라미터
  - SharingStarted.Eagerly: 즉시 공유를 시작하며, scope가 취소되면 중지 
  - SharingStarted.Lazily : 첫번째 collector가 나타나면 공유를 시작하고, scope가 취소되면 중지 
  - SharingStarted.WhileSubscribed : collector가 없어지고 몇초 뒤에 flow를 취소할지 지정 (지금 코드에서는 수집이 중단되고 5초가 지나면 upstream flow도 취소됩니다.) 

[이 글](https://medium.com/hongbeomi-dev/%EC%A0%95%EB%A6%AC-%EC%BD%94%ED%8B%80%EB%A6%B0-flow-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-android-dev-summit-2021-3606429f3c5f)을 통해 `SharingStarted.WhileSubscribed` 의 작동 방식을 더 잘 이해할 수 있습니다 :) 

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/46491ff0-34d2-4897-9747-6f2453753e64)

위의 그림에서 화면이 회전될 때는 빠른 전환을 위해 flow가 중단되면 안 되고 

(예를 들어 홈버튼을 눌러) 앱이 백그라운드 상태가 되면 리소스가 낭비되거나 앱이 크래시 되는 걸 막기 위해 flow를 중단해야 합니다. 

이를 위해 WhileSubscribed 함수의 인자로 타임아웃을 지정할 수 있습니다! 만약 지정한 타임아웃 이전에 collector가 flow를 수집하면 업스트림 flow가 중단되지 않습니다. 

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/8b9c5f88-8301-442a-94a9-5808b409e289)

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/ac1affc5-2712-4d5e-a0d3-03fcba2fa44f)


참고 자료 
- https://developer.android.com/kotlin/flow/stateflow-and-sharedflow
- https://readystory.tistory.com/207
- https://kotlinworld.com/233

2023-08-11 13:43 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +        }
아하 그렇군요 ! 그러면 바로 직전에 중복확인했던 닉네임만 뷰모델에 mutableStateflow로 설정해서 중복확인이 완료되면 해당 닉네임을 저장하고, 입력된 텍스트의 변화가 있을때, 현재 입력된값이랑 비교하는 방식은 어떤가요 ?  ?

2023-08-11 20:58 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +            started = SharingStarted.WhileSubscribed(PRODUCE_STOP_TIMEOUT)
아 그래서 시간을 지정해서 WhileSubscribed를 지정해줬던 거군요 !
남겨준 글 보고 SharingStarted의 요소들을 잘 활용하도록 더 노력해볼게용 감사합니다 👍

2023-08-11 20:59 UTC, sxunea approved these changes

2023-08-12 03:20 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/onboarding/nickname/NicknameViewModel.kt
> +        }
오홍 그럼 바로 직전에 입력해서 서버통신 완료한 닉네임만 임시 저장해두는 식으로 한번 구현해볼게요!

2023-08-12 07:03 UTC, merged