[feat] 위니피드, 마이피드 / Paging3 적용 + 로딩 프로그레스바 구현
team-winey/Winey-AOS pull request #108
Opened 2023-08-11 20:43 UTC by sxunea

- closed #99 

## 📝 Work Description

- 피드에 paging3 적용
- 페이지 사이에 로딩 프로그레스바 구현
- 좋아요,삭제 등 기존 로직 페이징, 소셜로그인에 맞게 수정

## 📣 To Reviewers
- 오늘 자정까지 리뷰 부탁드립니다 ! 
- 프로그레스바 색 뭐할까요 지금은 위니 형광노랑인데 ..

2023-08-11 20:51 UTC, sxunea commented
기록용 : 페이징된 recyclerview에 페이지 끝마다 로딩 프로그레스바 넣기
1. 다이얼로그로 표현 [(6d900e)](https://github.com/team-winey/Winey-AOS/pull/108/commits/2440b52ce5f2a6fffe22f542f5f3f33bc2a1348a)
2. MultiviewType ViewHolder + 추상화 + type으로 로딩 파악 [(945290f)](https://github.com/team-winey/Winey-AOS/pull/108/commits/945290fbbeab98ef31be4e651f1b41290b45dfa7))](https://github.com/team-winey/Winey-AOS/pull/108/commits/e72dce82cace0ebdb3b61d4e9262b968f83a756b}) [(e72dce8)](https://github.com/team-winey/Winey-AOS/pull/108/commits/e72dce82cace0ebdb3b61d4e9262b968f83a756b))](https://github.com/team-winey/Winey-AOS/pull/108/commits/e72dce82cace0ebdb3b61d4e9262b968f83a756b)
3. loadState에 따라 visibility 조절
4. loadStateAdapter 도입, repeatOnLifecycle이용해 탐지 [(ff6ddf1)](https://github.com/team-winey/Winey-AOS/pull/108/commits/ff6ddf168c2ee6e03499cbac5124de770a56f6a5)

2023-08-13 12:29 UTC, leeeha requested changes
페이징, LoadStateAdapter, SwipeRefresh, API 분리까지 넘넘 고생많았어!!!
백혜선 폼 미쳐따~~~!~!~! 💘💘

2023-08-13 12:29 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +                launch {
수집하는 flow가 여러 개가 아닌 경우는 launch 블록으로 한번 더 감싸주지 않아도 되는 거 같아요! 

참고) https://developer.android.com/topic/libraries/architecture/coroutines#restart

2023-08-13 12:29 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +                    viewModel.getWineyFeedListState.collectLatest { state ->
collect, collectLatest 함수의 차이점 따로 알아보겠습니당

2023-08-13 12:29 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
>              viewModel.getWineyFeed()
요기서 viewModel.getWineyFeed() 대신에 wineyFeedAdapter.refresh() 로 작성해도 동일하게 동작하는지 궁금하네요! PagingDataAdapter의 refresh() 함수는 호출 시 처음부터 데이터를 다시 로드한다고 해요! 

참고) https://leveloper.tistory.com/207

2023-08-13 12:29 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
> +                    notifyItemChanged(index)
요기도 submitData 함수를 사용할 수는 없는 건가요??

2023-08-13 12:29 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
> +                    )
요기도 데이터바인딩, 바인딩어댑터 사용해봐도 좋을 거 같아요 :)

2023-08-13 12:29 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedFragment.kt
> +                launch {
요기도 launch 블록으로 감싸지 않아도 될 거 같아요!

2023-08-13 14:12 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/data/source/pagingSource/BasePagingSource.kt
> +package com.android.go.sopt.winey.data.source.pagingSource
감사합니다 수정할게요 :)

2023-08-13 14:16 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/data/repository/FeedRepositoryImpl.kt
> +        Pager(PagingConfig(FEED_PAGE_SIZE, prefetchDistance = LOAD_DISTANCE)) {
현 페이지의 최하단으로부터 몇번째 아이템일때 다음 페이지를 부를지 지정해주는 요소입니다 ! 사용자가 마지막에서 두번째 아이템을 지나갈때 다음페이지를 불러오도록 설정했어요 😸

2023-08-13 14:29 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
> +                    )
오 좋은 의견감사합니다 반영해볼게요 👍

2023-08-13 14:29 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
> +                if (data != null) {
오 좋습니다 반영해볼게요 👍

2023-08-13 14:29 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
>                  executePendingBindings()
아 예전에 데이터바인딩 하려고했던 코드가 남아있네요 ㅎㅎㅎ 감사해요

2023-08-13 14:39 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
> +                    notifyItemChanged(index)
고려해보긴했는데pagingAdapter는 listAdapter랑 달리 currentList가 없어서 snapshot을 받아와야하는데 ItemSnapshotList를 다시 PagingData로 변환해주는 작업이 필요해서 저렇게 구현했습니다 ! 또 바뀐 리스트 전체를 submit 하는것보다는 좋아요를 누른 해당 아이템만 ui에 업데이트해주는 함수여서 notifyItemChanged로도 충분하다고 판단했습니다

2023-08-13 14:46 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +                launch {
헉 함수 수정하다 전에거 안지웠네요  ㅋㅋㅋㅋ ㅠㅠㅠ 꼼꼼한 리뷰 감사합니다

2023-08-13 14:46 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
> +                    notifyItemChanged(index)
위에 코멘트 참고해주시고 의견부탁드립니다 ~

2023-08-13 15:00 UTC, sxunea commented on app/src/main/res/layout/item_feed_loading_footer.xml
> +            app:layout_constraintTop_toTopOf="parent" />
눈물머금고 형광노랑 보내줍니다 ,,, ❤️

2023-08-14 12:21 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
> +                    notifyItemChanged(index)
- https://leveloper.tistory.com/202
- https://cliearl.github.io/posts/android/recyclerview-listadapter/
- https://stackoverflow.com/questions/62749303/how-can-we-get-entire-object-list-passes-to-the-pagingdataadapter-while-using-pa

위의 글들을 참고해보면 ListAdapter와 PagingDataAdapter 모두 백그라운드에서 DiffUtil을 사용하여 데이터를 정제한 뒤에 데이터를 불러오기 때문에, 최종적으로 UI 스레드에 새로운 데이터를 보여줄 때 끊김없이 부드럽게 나타난다고 해요! 

그리고 DiffUtil은 두 데이터셋을 받아서 그 차이를 계산해주는 클래스여서, 이를 이용하면 두 데이터셋을 비교한 뒤 그 중에서 변한 부분만을 파악하여 Recyclerview에 반영할 수 있다고 합니다! 즉, submitList, submitData 인자에 전체 리스트를 넘겨준다고 해서 전체 데이터를 갱신하는 건 아니고, 그 중에서 이전 데이터와 바뀐 부분만 파악하여 갱신합니다!

`adapter.snapshot().items` 를 이용하면 ListAdapter의 currentList 처럼  전체 리스트를 가져올 수 있는 거 같아요! 

다만, 여기서는 변경된 아이템의 position (index) 을 알 수 있기 때문에 `notifyItemChanged(index)` 사용하는 것도 괜찮은 방법인 거 같아요!

2023-08-14 12:29 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
여기 아래 코드에서 궁금한 점이 있는데요! `DiffUtil.ItemCallback`의 `areItemsTheSame` 함수를 오버라이딩 할 때는 두 객체가 동일한지 비교하게 되는데, 이때 보통 아이템을 유일하게 식별할 수 있는 id 값이나 `===` 연산자로 주소 값을 비교하는 거 같아요! 그런데 아래 코드에서 feedId 가 아니라, isLiked 로 WineyFeed 아이템을 식별한 이유가 있을까요?? 

만약 areItemsTheSame를 잘못 정의하면 모든 Item을 다 지우고 새 아이템을 Insert 하게 되므로, 기존의 notifyDataSetChanged()와 다를 것이 없어지기 때문에 주의해야 한다고 해요! 

참고) https://jminie.tistory.com/146?category=1040997

2023-08-14 16:32 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAdapter.kt
어 마침 방금 푸쉬한거에 해당 부분 수정되어있습니다 ㅎㅎㅎ
앱잼기간에 좋아요 상태를 반영할때 해봤던건데 수정이안되어있었네요 ... ! 감사합니다 👍

2023-08-14 16:42 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +                    viewModel.getWineyFeedListState.collectLatest { state ->
collect와 collectLatest 의 차이는 새로운 데이터가 들어왔을 때의 처리 방식인데요 collect는 새로운 데이터가 들어오면 이전 데이터의 처리가 끝난 후에 새 데이터를 처리하는데, 이와 달리 collectLatest는 그 이름처럼 기존 데이터 처리를 강제 종료하고 새롭게 들어온 데이터를 바로 처리합니다 !
따라서 paging을 사용하는 피드 부분은 collectLatest를 통해 사용자의 중복 요청을 중 제일 최근 데이터를 처리해 제공하면서 효율적인 반응이 가능합니다 

[paging 
lifecycleScope.launch {
  viewModel.flow.collectLatest { pagingData ->
    pagingAdapter.submitData(pagingData)
  }
}
> 공식문서](https://developer.android.com/topic/libraries/architecture/paging/v3-paged-data?hl=ko)

[collectLatest 공식문서](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/collect-latest.html)

2023-08-14 16:57 UTC, leeeha approved these changes
어푸! LGTM 👍👍

2023-08-14 16:59 UTC, merged