[mod] 마이 피드 / 상세페이지에서 삭제시 화면 처리
team-winey/Winey-AOS pull request #185
Opened 2023-09-02 17:24 UTC by sxunea

- closed #184 

## 📝 Work Description

- 상세페이지 이동 시 전 화면이 무엇인지(위니/마이) 알리기
-  전 화면에 따라 삭제 성공 시 화면 이동 및 스낵바 뜨도록 수정 구현

## 📣 To Reviewers
이제 진짜 끝이겠죠 😿 ❤️

2023-09-03 07:48 UTC, leeeha approved these changes
👍👍

2023-09-03 10:30 UTC, Sangwook123 approved these changes
👍👍👍👍👍

2023-09-05 13:57 UTC, leeeha requested changes
실행 시켜봤는데 마이페이지가 백스택에 남아있어서
다른 하단 탭 눌렀다가 뒤로가기 누르면 앱이 바로 종료되어야 하는데
마이페이지 프래그먼트로 돌아가버리는 이슈가 있네요..!! 확인 부탁드립니당 🙏

2023-09-06 01:10 UTC, sxunea commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
> +            bundle.putString(key, value)
상욱오빠 코드가 저렇게되어있길래 반복되는 코드 함수화하고 싶어서 맞춰서 저렇게 했는데 동의하면 같이 바꿔둬도 될까요 ? @Sangwook123

2023-09-06 01:53 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
> +            bundle.putString(key, value)
넵  !! Boolean이 더 좋겠습니다 👍👍

2023-09-06 05:34 UTC, sxunea commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
> +            bundle.putString(key, value)
넵 그럼 알림쪽도 같이 바꿔둘게요 ~

2023-09-09 06:56 UTC, leeeha approved these changes
프래그먼트 간의 데이터 전달, 그리고 백스택 관리까지..!! 까다로운 부분이었는데 에러 해결돼서 다행이다 🙏🙏 넘 고생해써!! 💘

2023-09-09 06:56 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
> +                arguments = null
`arguments?.clear()` 라는 함수도 따로 있는 거 같더라구요! 지금 코드와 동일하게 작동할 거 같아요!

2023-09-09 07:25 UTC, merged