Feature/UI wineyfeed view
team-winey/Winey-AOS pull request #19
Opened 2023-07-12 06:40 UTC by sxunea

- #7 

## 📝 Work Description

- 위니 피드 뷰 구현

## 📸 Screenshot
![device-2023-07-12-153516](https://github.com/team-winey/Winey-AOS/assets/81434152/7a6d024a-c8c7-4440-a667-4aabeefc164a)

## 📣 To Reviewers
- 안드화이팅안드짱~

2023-07-12 11:47 UTC, leeeha requested changes
생각보다 리뷰를 많이 단 거 같은데 확인 후 코멘트나 이모지 부탁드려요~~!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedAlertDialog.kt
> +        dialog?.window?.setBackgroundDrawable(ColorDrawable(Color.TRANSPARENT))
요 내용도 BindingDialogFragment의 onStart 함수 안에 들어가면 좋을 거 같습니다!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +            dialog.isCancelable = false
`dialog.isCancelable = false` 이 코드도 WineyFeedAlertDialog의 onViewCreated 함수 안에 넣으면 좋을 거 같아요!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +            dialog.show(activity?.supportFragmentManager!!, "ConfirmDialog")
태그 문자열은 companion object 안에서 상수로 정의해주면 더 좋을 거 같습니다! 

그리고 널을 단정하는 `!!` (non-null assertion)은 사용을 지양하는 게 좋다고 알고 있습니다. `!!`을 사용하지 않고 코드를 작성할 수 있는 방법은 없을까요??

2023-07-12 11:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedHeaderAdapter.kt
> +    override fun getItemCount() = 1
아주 사소한 부분이지만 시간적인 여유가 있다면 [이 코드](https://github.com/GO-SOPT-ANDROID/chaeyeon-jeon/blob/develop/app/src/main/java/org/android/go/sopt/presentation/main/home/RepoHeaderAdapter.kt) 처럼 상수화를 습관적으로 하면 좋을 거 같습니다!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/drawable/box_gray_radius_5.xml
> +</shape>
[코드 컨벤션](https://www.notion.so/Code-Convention-d39ec34c2d1240f297f6027b8f9839c3) 문서 참고해서 drawable 파일 네이밍 수정 부탁드려요! ex) `shape_gray_fill_5_rect`

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/drawable/ic_caution.xml
> +</vector>
아이콘 네이밍은 `ic_[where]_[what]` 이것처럼 어디에서 사용되는지도 명시해주면 좋을 거 같아요! 

https://www.notion.so/drawable-file-name-f532b934e6434c6695397a234072d254 -> 컨벤션 문서 참고!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/drawable/ic_floatingbtn.xml
> +</vector>
아마 이 부분은 글 작성을 나타내는 아이콘 같은데, `ic_wineyfeed_upload` 이런 식으로 네이밍 해도 좋을 거 같습니다!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/drawable/img_app_bar.xml
> +</vector>
이미지도 `img_[where]_[what]` 요런 식으로 네이밍 맞추는 걸로 해요~~! 컨벤션 문서 참고!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
원래대로 0dp가 좋을 거 같습니다! ConstraintLayout 안에서 부모 너비에 맞출 때는 0dp (match constraint)가 권장된다고 해요!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_height="wrap_content"
바텀 네비 높이는 56dp가 권장되어서 크기를 고정해뒀는데 `wrap_content`로 설정해도 별 차이가 없던가요?? 피그마 상에도 56dp로 되어있긴 합니다!

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/layout/dialog_wineyfeed_alert_no_goal.xml
> +<?xml version="1.0" encoding="utf-8"?>
다이얼로그 프래그먼트를 상속 받는다는 점에서 `fragment_wineyfeed_no_goal_dialog` 이런 식으로 네이밍 하는 건 어떨까요??

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/values/dimens.xml
> +</resources>
이 파일은 어디에서 사용되는지 알 수 있을까요??

2023-07-12 11:47 UTC, leeeha commented on app/src/main/res/values/strings.xml
> +    <string name="dialog_setgoal">목표 설정하기</string>
지금은 위니 피드 다이얼로그의 string 리소스들 네이밍 이렇게 해도 문제 없는데 
앞으로 다른 화면에서도 다이얼로그가 사용될 수 있기 때문에 `[where]_dialog_[what]` 이렇게 네이밍 하는 건 어떨까요??

2023-07-12 12:25 UTC, Sangwook123 reviewed
고생하셨습니다 !

2023-07-12 12:25 UTC, Sangwook123 commented on app/src/main/res/layout/activity_main.xml
> +            android:layout_width="match_parent"
부모 너비에 맞출때는 0dp가 권장된다는건 저도 지금 알았네요! 👍👍

2023-07-12 12:25 UTC, Sangwook123 commented on app/src/main/res/layout/item_wineyfeed_post.xml
> +        <de.hdodenhof.circleimageview.CircleImageView
요런것도 있군요 배워갑니다 !

2023-07-12 13:48 UTC, sxunea commented
@leeeha @Sangwook123 오늘의교훈 컨벤션은 한번읽고 안외워진다,,,,메모 
리뷰감사해용 수정완료 😻

2023-07-13 06:25 UTC, leeeha approved these changes
어푸!

2023-07-13 06:25 UTC, merged