[UI] #1 컬러, 폰트 적용
team-winey/Winey-AOS pull request #2
Opened 2023-07-03 03:29 UTC by Sangwook123

## 📝 Work Description

- 디자인 시스템 적용
- 컬러/폰트

## 📣 To Reviewers

- 추가로 수정해야 할 사항 있으면 말씀부탁드립니다 !

2023-07-03 03:44 UTC, leeeha commented
PR 올릴 때 우측에 Projects, Milestone도 세팅해주세요~! (지금은 제가 설정해뒀어요)

2023-07-03 09:52 UTC, leeeha requested changes
리뷰 확인하고 수정 부탁드려요! 기초 세팅 고생했어요 👍

2023-07-03 09:52 UTC, leeeha commented on app/src/main/res/font/winey_font.xml
> +</font-family>
아래처럼 폰트 두께에 따라 `font-family`를 개별적으로 설정해야 두께가 달라지는 걸로 알고 있어요! 

안드 3차 세미나 자료에 오류가 있었다고 그때 당시 단톡방에 공지가 올라왔었습니다! 

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/f8144dec-8389-412e-999f-c03841c0378d)

저 또는 채연이 세미나 레포 참고해서 다시 수정 부탁드립니다 :) 

폰트 두께에 따라 개별적으로 font-family xml 파일을 만들어줘야 해요! 

- [채연 세미나 레포 - 폰트 설정 참고](https://github.com/GO-SOPT-ANDROID/chaeyeon-jeon/tree/develop/app/src/main/res/font)
- [font-family 개별 설정](https://github.com/GO-SOPT-ANDROID/haeun-lee/tree/develop/app/src/main/res/font)
- [textAppearance 설정](https://github.com/GO-SOPT-ANDROID/haeun-lee/blob/develop/app/src/main/res/values/text_appearance_types.xml)

2023-07-03 09:52 UTC, leeeha commented on app/src/main/res/values/styles.xml
> +        <item name="lineHeight">23dp</item>
textSize <= lineHeight 이어야 할 거 같습니다!

2023-07-03 09:52 UTC, leeeha commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">14dp</item>
11로 크기 바꿔야 할 거 같네요! 그리고 [dp와 sp 단위의 차이점](https://woovictory.github.io/2019/01/03/Android-Diff-of-DP-SP/) 알고 넘어가면 좋을 거 같아요! 

지금은 dp로 설정했으니까 시스템 설정 값과 상관없이 항상 일정한 텍스트 크기를 유지할 것으로 보입니다!

2023-07-03 10:24 UTC, Sangwook123 commented on app/src/main/res/values/colors.xml
> +    <color name="yellow">#FFCCFC56</color>
오 넵! 그렇게 네이밍하는게 더 좋을것 같네요 !

2023-07-03 10:48 UTC, Sangwook123 commented on app/src/main/res/font/winey_font.xml
> +</font-family>
제가 이해하기론 하나의 폰트에 각각의 스타일이 존재할땐 하나의 폰트 패밀리로 묶는게 가능하다고 알고있습니다 !
[https://github.com/sopt-makers/sopt-android/blob/develop/app/src/main/res/font/sopt_font.xml](url)
현재 사용하는 글꼴이 pretendard 하나라서 메이커스 레포 참고해서 font-family 설정을 해봤고 실제로 레이아웃에서도 두께설정이 제대로 되고있음을 확인했습니다 !

혹시 제가 잘못 이해한걸까요..?

2023-07-03 10:56 UTC, Sangwook123 commented on app/src/main/res/values/styles.xml
> +        <item name="android:letterSpacing">-0.025</item>
이부분은 디자이너 분들께서 자간 -2.5%가 이상적이라고 하시고 이렇게 지정해두셔서 이를 letterSpacing속성에 맞게 -0.025로 지정했습니다 !

2023-07-03 10:58 UTC, Sangwook123 commented on app/src/main/res/values/styles.xml
> +<?xml version="1.0" encoding="utf-8"?>
넵 ! text_apprearance.xml로 리네임 하겠습니다 !

2023-07-03 11:08 UTC, Sangwook123 commented on app/src/main/res/values/styles.xml
> +        <item name="lineHeight">23dp</item>
수정하겠습니다 !

2023-07-03 12:09 UTC, sxunea commented on app/src/main/res/font/winey_font.xml
> +</font-family>
@Sangwook123 fontWeight이 다르지만 하나의 폰트를 사용하기 때문에 하나의 fontFamily로 묶는방법에 문제는 없습니다 ! 하지만 각각의 파일을 따로 만드는게 수정 및 관리가 용이해서 weight별 font-family를 만드는걸 추천해봅니다 ..!!

2023-07-03 12:10 UTC, sxunea commented on app/src/main/res/font/winey_font.xml
> +</font-family>
https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml?hl=ko 에서도 해당 방법을 사용하고있구요 !

2023-07-03 13:54 UTC, sxunea approved these changes

2023-07-03 14:28 UTC, leeeha approved these changes
굿!

2023-07-03 14:28 UTC, merged

2023-07-07 01:40 UTC, l2hyunwoo commented on app/src/main/res/font/winey_font.xml
> +</font-family>
@leeeha @sxunea @Sangwook123 안녕하세요 그때 세미나를 진행했던 사람인데요, AS가 너무 늦은 것 같아서 이렇게라도 해결책 공유드립니다.

[pophory-android/pophory_font](https://github.com/TeamPophory/pophory-android/blob/develop/app/src/main/res/font/pophory_font.xml)
[pophory-android/type.xml](https://github.com/TeamPophory/pophory-android/blob/develop/app/src/main/res/values/type.xml)

그때 제가 잘못 설명한 부분이 type.xml에서 fontWeight을 사용하라고 했던 것 같은데, 사실은 android:textFontWeight 속성을 사용해야 정상적으로 들어갑니다. 굳이 파일 분리 여러개 할 필요가 없이 구현할 수 있으니 이점 참고해주셔도 좋을 것 같습니다.

2023-07-07 03:52 UTC, leeeha commented on app/src/main/res/values/styles.xml
> +        <item name="android:letterSpacing">-0.025</item>
확인 완료!

2023-07-07 03:54 UTC, leeeha commented on app/src/main/res/font/winey_font.xml
> +</font-family>
오오 `android:textFontWeight` 속성으로 지정하는 방법도 있군요!! 정정해주셔서 감사합니다 👍👍