[feat] FCM 푸쉬알림 / 푸쉬알림 구현
team-winey/Winey-AOS pull request #229
Opened 2023-12-05 18:21 UTC by Sangwook123

- closed #226 

## 📝 Work Description
- [x] gradle세팅
- [x] 앱에 firebase추가
- [x] 푸쉬알림 구현
- [x] 알림동의 구현

## 📸 Screenshot

## 📣 To Reviewers

앱이 백그라운드일때만 알림이 오도록 구현했습니다.

2023-12-11 10:55 UTC, leeeha requested changes
구현하느라 넘 고생하셨습니다!! 👍👍👍

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
> +            else -> null
else -> null 은 안 적어도 될 거 같네욤!

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
>      }
안스에서 보니까 더 이상 사용되지 않는 변수나 상수들도 있던데 삭제해주면 좋을 거 같아요!

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
> +
지금처럼 연관된 상수들은 NotiType 같은 enum class로 묶는 게 좋을 거 같아요!! 

화면 네비게이션과 관련된 key 값들도 enum이나 sealed class로 묶어서 리팩토링 해볼까 생각하고 있습니다!

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainViewModel.kt
> +            }
중괄호 블록은 없어도 될 거 같네요~!

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
>                          snackBar(binding.root) { state.msg }
원래 로직이 토큰 만료되면 MainViewModel에서 로그아웃 메소드 실행하고 
메인 액티비티에서 logoutState 관찰해서 로그인 화면으로 넘어가는 걸로 알고 있는데 
여기서도 로그인 화면으로 바로 전환하게 만든 이유가 있을까요??

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
> +                            binding.ivMypageAgree.transitionToEnd()
오홍?! 버튼 토글할 때도 모션 레이아웃을 적용할 수 있군요! 👍

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
> +                }
```kotlin
lifecycleScope.launch {
  val data = dataStoreRepository.getUserInfo().first()
  val newData = data?.copy(fcmIsAllowed = true)
  dataStoreRepository.saveUserInfo(newData)
}
```

중복되는 위의 내용을 함수화 시키면 좋을 거 같습니다~!

2023-12-11 10:55 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
> +    private fun updateSwitchState(data: User) {
'무엇을' switch 하는 건지 바로 알 수 있도록 함수명에 힌트를 주면 좋을 거 같아요~!

2023-12-11 10:55 UTC, leeeha commented on app/src/main/res/xml/fragment_my_page_xml_cl_mypage_agree_scene.xml
> +</MotionScene>
우왕! 모션 레이아웃 코드 처음 보네요! 👍👍 

근데 xml 파일 이름이 다소 긴 거 같아서 `mypage_noti_agree_motion_scene.xml` 이 정도의 이름도 괜찮을 듯 합니다! 

아니면 특별히 지금처럼 이름을 지은 이유가 있을까요??

2023-12-11 10:58 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
> +
이 부분 때문에 request changes 버튼 눌렀습니다 ㅎㅎ

2023-12-11 19:31 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
> +        val uniId: Int = (System.currentTimeMillis() / 7).toInt()
uniId라는 변수명은 unique identifier의 줄임말로, 고유 식별자를 의미하는 네이밍으로 쓰였는데 지금보니 모호해 보이는 부분이 있네요 ! 조금 더 구체적인 네이밍 고려해보겠습니다 !

2023-12-21 05:39 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
>                          snackBar(binding.root) { state.msg }
http응답이 401일때만 로그아웃메소드가 실행되어서 404등 다른 실패응답에는 로그아웃 처리가 제대로 되지 않아서 지금과 같이 구현했습니다만 지금처럼 일괄처리하는 방식보다는 404만 추가대응하는 방식이 나아보여서 다시 수정했습니다.

2023-12-21 05:39 UTC, Sangwook123 commented on app/src/main/res/drawable/ic_mypage_switchoff.xml
> +</vector>
사용하지 않아서 삭제했습니다 !

2023-12-21 05:39 UTC, Sangwook123 commented on app/src/main/res/xml/fragment_my_page_xml_cl_mypage_agree_scene.xml
> +</MotionScene>
수정하겠습니다 !!

2023-12-23 08:37 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/ActivityLifecycleHandler.kt
> +class ActivityLifecycleHandler(private val application: Application) :
생성자의 인자로 application을 넘겨줘야 하는 이유가 궁금합니다!

2023-12-23 08:37 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
> +        return (System.currentTimeMillis() / 7).toInt()
7로 나누는 이유가 있을까요?!

2023-12-23 08:37 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
> +    private fun createAndShowNotification(remoteMessage: RemoteMessage, uniqueIdentifier: Int, pendingIntent: PendingIntent) {
음 개인적으로 함수명에 and를 사용하는 것은 지양하는 게 좋을 거 같다는 생각이 듭니다! 
가독성을 너무 해치지 않는 선에서, 최대한 한 함수는 하나의 기능을 담당하는 게 좋을 거 같아서요! 
여기서도 create, show 라는 각 동작에 대해 별도의 함수로 분리하는 게 어떨까요?! 
그러면 나중에 notification builder 생성 코드를 수정할 일이 있을 때 좀 더 편할 거 같습니다 :)

2023-12-23 08:37 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/MainActivity.kt
> +        }
어라랏 여기서 notiType에 따라 다른 함수가 실행되는 게 아니라, 몇몇은 동일한 함수를 실행시키네요?! 그러면 when문으로 구분하는 이유가 없어지는 거 같은데,, 이 부분에 대한 의견 궁금합니다!

2023-12-23 08:37 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
> +                }
isAllowed가 true든 false든 patchUserInfo 함수를 실행시켜야 한다면, when 블록 바깥에서 한번만 호출하면 될 거 같아요!

2023-12-23 08:37 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/model/NotificationType.kt
> +}
러넥트에서 enum class 자체를 인텐트의 부가 데이터로 넘기는 코드를 작성했는데, 아래 사진처럼 enum class가 `Serializable?` 타입으로 인식되더라구요! 그래서 getCompatibleSerializableExtra 같은 확장함수 이용해서 이넘 클래스 자체를 부가 데이터로 주고 받을 수 있게 했습니다! 

<img width="681" alt="스크린샷 2023-12-23 오후 5 31 57" src="https://github.com/team-winey/Winey-AOS/assets/68090939/6b6fc784-21ad-4328-8aec-b9e4984d3c5d">

```kotlin
enum class CourseDetailRootScreen {
    COURSE_STORAGE_SCRAP,
    COURSE_DISCOVER,
    COURSE_DISCOVER_SEARCH,
    MY_PAGE_UPLOAD_COURSE
}
```

```kotlin
private fun initIntentExtraData() {
    intent.getCompatibleSerializableExtra<CourseDetailRootScreen>(EXTRA_ROOT_SCREEN)?.let {
        rootScreen = it
    }
    publicCourseId = intent.getIntExtra(EXTRA_PUBLIC_COURSE_ID, 0)
}
```

이렇게 하면 굳이 이넘 클래스가 key라는 문자열 속성을 가질 필요가 없어서 좋은 거 같아요!

2023-12-23 08:48 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/model/NotificationType.kt
> +}
참고로 함수를 더블 클릭하고, Ctrl + P 누르면 함수의 인자 타입에 대해 알 수 있습니다 :)

2023-12-27 18:21 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
> +    private fun createAndShowNotification(remoteMessage: RemoteMessage, uniqueIdentifier: Int, pendingIntent: PendingIntent) {
넵 수정하겠습니다

2023-12-27 18:21 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/ActivityLifecycleHandler.kt
> +class ActivityLifecycleHandler(private val application: Application) :
불필요한 인자네요 수정하겠습니다 !

2023-12-27 18:22 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
> +        return (System.currentTimeMillis() / 7).toInt()
특별한 이유는 없습니다 ! 유니크한 고유 식별자를 만들기위해서 사용한 방식입니다.

2023-12-27 18:45 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/presentation/model/NotificationType.kt
> +}
참고하겠습니다 !! 근데 지금같은 경우에는 fcm알림으로 날아오는 데이터에 notitype이 포함되어있고 그걸 구분하기위해서 해당 키값을 이넘클래스에 포함시켜주었습니다.

2023-12-28 14:51 UTC, leeeha commented on app/src/main/java/org/go/sopt/winey/presentation/model/NotificationType.kt
> +}
아아 서버에서 저 문자열들로 노티 타입을 구분하는군요!! 그러면 지금처럼 구현하는 게 좋을 거 같습니다!

2023-12-28 14:55 UTC, leeeha approved these changes

2023-12-29 17:59 UTC, sxunea approved these changes
리뷰 늦어져서 미안합니다 고생했어요 😭

2023-12-29 17:59 UTC, sxunea commented on app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
> +        CoroutineScope(Dispatchers.IO).launch { dataStoreRepository.saveDeviceToken(token) }
Dispatchers.IO 으로 지정되어야하는 이유가 있을까요 ? FCM 자체가 백그라운드 스레드에서 호출된다고 알고 있어서 별도 스코프를 지정하지 않아도 될까하는데 궁금합니다 ! 자세히 공부해본 적은 없어서 아니라면 알려주세요 😮 

> All methods are invoked on a background thread, and may be called when the app is in the background or not open

2023-12-29 17:59 UTC, sxunea commented on app/src/main/java/org/go/sopt/winey/data/source/AuthDataSource.kt
> +    suspend fun patchAllowedNotification(
patchAllowedNotification 보다는 patchNotificationAgreement와 같은 네이밍해줘도 좋을 것 같아요 !

2023-12-29 17:59 UTC, sxunea commented on app/src/main/res/xml/mypage_noti_agree_motion_scene.xml
> +<MotionScene
😲 👍

2023-12-30 13:56 UTC, Sangwook123 commented on app/src/main/java/org/go/sopt/winey/configuration/WineyMessagingService.kt
> +        CoroutineScope(Dispatchers.IO).launch { dataStoreRepository.saveDeviceToken(token) }
맞습니다! 별도의 백그라운드 스레드에서 실행되기때문에 스코프 지정이 필요없습니다. 그런데 Dispatcher.default는 최대 12개의 스레드, 즉 12개의 작업만 한번에 할 수 있는 반면, Dispatcher.io는 최대 64개의 스레드를 사용한다고 합니다. 따라서 한 가지의 무거운 작업을 할때는 Dispatcher.default, 대기시간이 있는 가벼운 입출력 작업을 할때는 Dispatcher.io가 성능향상에 도움이 된다고 합니다.

2024-01-10 10:08 UTC, merged