[feat] 마이페이지 / 유저정보 받아오기 서버연결
team-winey/Winey-AOS pull request #35
Opened 2023-07-15 18:27 UTC by Sangwook123

- closed #24 

## 📝 Work Description

 유저정보 DTO 작성
 서비스, 레포지토리 작성
 마이페이지모델 데이터 클래스
 매핑함수 작성
 마이페이지뷰 데이터 바인딩
 서버통신 유저정보 받아오기 구현
 UI state 분기별로 작성

## 📸 Screenshot

<img width="300" src="https://github.com/team-winey/Winey-AOS/assets/113014331/0118291d-d020-4042-bfad-0d26d765ec33" />

## 📣 To Reviewers
안드 화이팅 !

2023-07-16 05:04 UTC, sxunea requested changes
고생하셨습니다 안드짱
hilt에 코루틴 서버통신까지 최고 💯

2023-07-16 05:04 UTC, sxunea commented on app/src/main/res/layout/fragment_my_page.xml
> +                    android:text="@{String.valueOf(`LV. `) + data.userLevel}"
이 방법도 좋지만 bindingAdapter에 해당 형식의 함수를 만들어둬도 편리할것같아요 !  ~'원 절약'에 대한 함수를 applyNumberFormatToMoney로 만들어뒀으니 참고해주세용

2023-07-16 05:04 UTC, sxunea commented on app/src/main/res/layout/fragment_my_page.xml
> +                        android:text="@{String.valueOf(`D-`) + data.targetDay}"
D-, 원 이런것들도 다 만들어두면 재사용하기 편리할것같습니다

2023-07-17 07:07 UTC, leeeha requested changes
힐트 적용해서 서버 연결하는 거 어려웠을 텐데 정말루 고생하셨슴다!!!

2023-07-17 07:07 UTC, leeeha commented on app/src/main/res/layout/fragment_my_page.xml
> +                    android:text="@{String.valueOf(`LV. `) + data.userLevel}"
string 리소스 파일 따로 만들어주세요~!

```xml 
android:text="@{@string/mypage_user_level(data.userLevel)}"
```

2023-07-17 07:07 UTC, leeeha commented on app/src/main/res/layout/fragment_my_page.xml
> +                        android:text="@{data.targetMoney+'원'}"
요것도 string 리소스 따로 빼는 걸로 해요~!

2023-07-17 11:26 UTC, leeeha approved these changes

2023-07-17 11:27 UTC, merged