[feat] main / 바텀네비게이션 바 구현
team-winey/Winey-AOS pull request #6
Opened 2023-07-05 08:47 UTC by Sangwook123

- closed #1 

## 📝 Work Description

- manifest파일에 hilt 사용을 위한 application name 설정
- 바텀 네비게이션 바 구현

## 📸 Screenshot

## 📣 To Reviewers
수정사항 있으면 말씀 부탁드립니다 !

2023-07-05 10:01 UTC, leeeha requested changes
- 리뷰 참고해서 약간 수정 부탁드려요~~!
- 그리고 이미 닫힌 이슈를 참조하기 보다는, `이슈 생성 > feature 브랜치 생성 > 커밋, push > PR 올릴 때 이슈 참조` 이렇게 하는 게 더 좋을 거 같아요! 작은 작업이더라도 이슈 생성하는 습관 들여봅시다!

2023-07-05 11:05 UTC, Sangwook123 commented on app/src/main/AndroidManifest.xml
> +        android:name=".Application"
👍👍 변경하도록 하겠습니다 !

2023-07-05 11:41 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
> +            .commit()
잘 읽어보았습니다! 불필요한 객체생성을 방지한다는 점에 큰 장점이 있는 방식이네요 ! 참고해서 코드 수정하도록 하겠습니다.

2023-07-05 11:44 UTC, Sangwook123 commented on app/src/main/res/values/themes.xml
> +        <item name="background">@color/gray_0</item>
bnv 배경색상으로 사용하려고 만들어두었는데 누락되었네요 수정해놓겠습니다.

2023-07-05 11:46 UTC, Sangwook123 commented on app/src/main/res/drawable/main_bnv_menu_color_selector.xml
> +</selector>
문서 참고해서 수정하겠습니다 !

2023-07-05 13:49 UTC, leeeha requested changes
Material 3 컬러 시스템 공식문서와 3차 세미나 자료 읽어보고 컬러 지정을 다시 하면 좋을 거 같습니다! 조금만 더 화이팅!!

2023-07-05 13:49 UTC, leeeha commented on app/src/main/res/layout/activity_main.xml
> +            android:background="?background"
요 부분 `andorid:background="?colorSurface"` 로 바꾸면 좋을 거 같습니다!

2023-07-05 13:49 UTC, leeeha commented on app/src/main/res/drawable/sel_main_bnv_icon_color.xml
> +</selector>
[공식문서](https://github.com/material-components/material-components-android/blob/master/docs/components/BottomNavigation.md#container-attributes) 참고해서 바텀 네비게이션의 배경색, 아이콘과 텍스트 색상은 어떻게 네이밍 해야 좋은지 알아보면 좋을 거 같아요! 

아래는 디폴트 스타일인데요! 

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/8007313e-49ab-4b32-957f-8dc2854f0965)

이렇게 themes.xml 파일에서 컬러 지정하고 

```xml
<!-- Navigation Bar Container color -->
<item name="colorSurface">@color/gray_0</item>

<!-- Navigation Bar Icon/Text Active color -->
<item name="colorOnSurface">@color/purple_400</item>

<!-- Navigation Bar Icon/Text Inactive color -->
<item name="colorOnSurfaceVariant">@color/gray_300</item>
```

selector 파일에서는 다음과 같이 사용하면 됩니다! 

```xml 
<?xml version="1.0" encoding="utf-8"?>
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:color="?colorOnSurface" android:state_checked="true" />
    <item android:color="?colorOnSurfaceVariant" android:state_checked="false" />
</selector>
```

2023-07-05 13:49 UTC, leeeha commented on app/src/main/res/drawable/sel_main_bnv_icon_color.xml
> +</selector>
참고 자료 

- [3차 세미나](https://www.notion.so/go-sopt/3-4e415b9f8d27436586b6baf3d13e1d44#6f0e8a4aa8004e0fb5149ede5346b336)
- [Material 3](https://m3.material.io/styles/color/the-color-system/key-colors-tones#5fdf196d-1e21-4d03-ae63-e802d61ad5ee) 

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/c8929cdc-4e4c-4fd9-bcdb-a490018432d2)

2023-07-05 13:56 UTC, Sangwook123 commented on app/src/main/res/drawable/sel_main_bnv_icon_color.xml
> +</selector>
이부분 저도 네이밍과 컬러를 어떻게 지정해야할지 명확하지 않았었는데 감사합니다 !! 😊😊😊

2023-07-06 02:39 UTC, leeeha approved these changes
고생하셨습니다!!!

2023-07-06 02:41 UTC, merged