[refactor] 마이페이지, 추천위니 / 리팩토링
team-winey/Winey-AOS pull request #96
Opened 2023-08-01 15:52 UTC by Sangwook123

- closed #93

## 📝 Work Description

- 마이페이지, 추천위니 StateFlow 사용
- 프래그먼트 이동시, 바텀네비게이션 아이콘 동기화

## 📸 Screenshot

## 📣 To Reviewers
뒤로가기 버튼을 눌렀을때나, 목표설정 다이얼로그에서 마이페이지로 이동하였을때 바텀네비게이션 아이콘도 따라서 변경되도록 하였습니다.

2023-08-02 04:47 UTC, leeeha requested changes
코멘트 참고해주세요 :) 리팩토링 고생하셨슴당!!

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/MainActivity.kt
> +    }
굿굿!! 이런 오류가 있는지 몰랐는데 역시 꼼꼼한 우리 팀 QA 👍👍

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
> +        bottomNav.selectedItemId = R.id.menu_mypage
BottomNavigationView 변수가 여기에서만 사용되니까 굳이 전역으로 만들 필요는 없을 거 같아요! 
그리고 함수화 시켜주는 게 좋을 거 같아요!

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +                }
오호 StateFlow 상태에 대한 처리는 이렇게 할 수 있군요! 저도 Flow 공부 빨리 하겠습니닷!!
LiveData 보다 좋은 점이 뭔지 궁금하네요!

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
>          viewModel.getUser()
onResume 함수에서 getUser 실행하는 이유는 바텀시트로 목표 설정하고 나서, 그 결과를 뷰에 보여주기 위함인가요??

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
>                  }
Ktlint가 코드 스타일 점검해주니까 좋네요! 

PR 올리기 전에 터미널에서 `./gradlew ktlintCheck` 실행해서 스타일 검사할 수 있고, 커밋할 때마다 검사하고 싶으면 hook 등록하면 된다고 해요! 노션 참고해주세요 :)

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                    }
이제 메인 뷰모델 대신 DataStore에서 유저 데이터를 가져오는 방식으로 바꿀 예정인거죠?? 화이팅!

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                        binding.tilTargetAmountSetAmount.error = " "
이거는 왜 빈 문자열로 초기화 하는지 알 수 있을까요??

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                            )
util 패키지 안에 getColor 확장함수 있을 거예요! 그거 사용하면 코드량 줄일 수 있어서 편해요!!

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
>                          )
중복되는 코드들이 꽤 보이는데, 저는 세미나 코드에서 

![image](https://github.com/team-winey/Winey-AOS/assets/68090939/73890311-554e-466c-83c5-7718c2149bc4)

이런 식으로 데이터바인딩 이용해서 TextInputLayout에 에러 상태 표시했어요! 참고해주세요 :)

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                    }
이것도 데이터바인딩 이용해서 xml에서 처리할 수 있을 거 같아요! 
xml에서 뷰모델의 데이터 참조해서, 그에 따라 뷰가 바뀌도록

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
>          )
!! (non-null) 연산자를 사용하지 않고 코드를 짤 수 있는 방법은 없을까요??

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
>                  .onSuccess { response ->
Log 대신 Timber 사용하면 좋을 거 같아요! 그리고 okhttp로 서버통신 성공/실패 여부를 알 수 있기 때문에 Log를 일일이 찍지 않아도 될 거 같습니다 :)

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                    }
서버 통신에 실패했을 때, 그 에러 메시지를 스낵바로 띄워도 괜찮을 듯 합니다! (위니 피드 혜선이 코드 참고)

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
> +        const val MAX_DAY_LENGTH = 3
목표 기간, 금액 범위 제한 코드에서 숫자들이 하드코딩 되어 있는데 const로 상수화 시켜주세요!

그리고 범위 체크 함수에서 if-else가 주로 사용되고 있는데, 인덴트 depth를 줄여 가독성을 높이려면 if-else 보다는 early return 방식이 더 좋다고 들었어요! 정답은 아니지만 참고하면 좋을 거 같아요 :) 

- https://velog.io/@jangws/9.-Else-if와-Else를-피하고-Early-Return하자
- https://github.com/orgs/woowacourse-precourse/discussions/358

2023-08-02 04:47 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/recommend/RecommendFragment.kt
> +                    }
에러 상태에 대한 처리도 해주면 좋을 거 같아요! ex) 스낵바로 에러 메시지 띄우기 
개발자 입장에서는 에러 로그를 볼 수 있지만, 유저는 비어있는 화면을 보고 당황할 수도 있을 거 같아서,,

2023-08-02 08:25 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +                }
저는 StateFlow가 LiveData와 달리 뷰의 생명주기에 종속되지 않는다는 점이 좋았습니다 !

2023-08-02 08:31 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/MyPageFragment.kt
>          viewModel.getUser()
넵! 기존에 observer함수는 뷰의 생명주기에 따라 종속되었기 때문에 onResume시 실행을 해 주어야 뷰에 반영이 되었었는데 stateFlow의 collect사용 시에도 onResume에서 getUser를 해주어야 하는지는 한 번 확인해보겠습니다 !

2023-08-02 08:31 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
>          )
수정해보겠습니다 !

2023-08-02 09:35 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
> +        bottomNav.selectedItemId = R.id.menu_mypage
findBiewById에서 리턴하는 데이터의 타입을 추론할 수 있기 때문에, bottomNav 변수의 선언과 초기화를 한꺼번에 해도 될 거 같아요! 

`val bottomNav = requireActivity().findViewById(R.id.bnv_main)`

2023-08-02 09:42 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                        binding.tilTargetAmountSetAmount.error = " "
엇 그렇군요..!! TextInputLayout 자체에서 에러 텍스트 표시 기능을 제공하기 때문에 그대로 활용하면 좋을 거 같아요!

2023-08-02 09:54 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountViewModel.kt
>                  .onSuccess { response ->
이것도 현재 코드에 반영되어 있지 않네요..!

2023-08-03 12:12 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
> +        bottomNav.selectedItemId = R.id.menu_mypage
requireActivity().findViewById() 메서드는 뷰를 반환하는데, 해당 뷰의 타입은 알 수 없기 때문에 컴파일러가 정확한 타입을 추론하지 못할 수도 있다고 합니다 ! 따라서 다음과 같이 수정하였습니다 !
 `val bottomNav : BottomNavigationView = requireActivity().findViewById(R.id.bnv_main)`

2023-08-03 12:17 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                        binding.tilTargetAmountSetAmount.error = " "
에러 텍스트가 에러상태가 아닐때도 보여야해서 textInputLayout 에러 텍스트 기능도 그렇게 가능할까요 ?

2023-08-03 16:36 UTC, merged

2023-08-04 04:34 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDialogFragment.kt
> +        bottomNav.selectedItemId = R.id.menu_mypage
오호 타입 추론이 안 된다는 걸 몰랐네요!! 코멘트 감사합니다 :)

2023-08-04 05:14 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
> +                        binding.tilTargetAmountSetAmount.error = " "
아하 피그마 확인하고 오니까, 왜 이렇게 코드를 짰는지 이해가 되네요! 

https://github.com/material-components/material-components-android/blob/master/docs/components/TextField.md

위의 문서 확인해보면 이런 경우에 TextInputLayout에서는 보통 `app:helperText` 속성을 사용하는 거 같은데 

helper text 를 고정으로 해두고, `app:errorEnabled` 속성을 바꿔가면서 색상을 변화시키는 방법도 있을 거 같아요! 

에러 색상은 `app:errorTextColor` 이 속성으로 지정할 수 있구요!

2023-08-05 02:28 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/TargetAmountBottomSheetFragment.kt
>                          )
>AAC DataBinding 은 레이아웃과 데이터 사이의 다리 역할을 하는 프레임워크입니다. 데이터바인딩은 개발자가 작성해야 하는 보일러 플레이트 코드를 확연히 줄여주고, 개발자로 하여금 **데이터를 처리하는 로직에만 집중**할 수 있게 해 줘 생산성을 향상해줍니다. 데이터바인딩은 lifecycle 을 알고 있기 때문에 UI 가 화면에 보이는 경우에만 트리거 됩니다.

데이터바인딩의 장점이라고 하네요! 다만, 바인딩 클래스 파일들이 만들어지면서 앱의 용량이 커지고, 빌드 속도가 느려지는 등의 단점도 있다고 합니다.