[refactor] 위니 피드, 마이 피드 / 리팩토링
team-winey/Winey-AOS pull request #98
Opened 2023-08-03 18:28 UTC by sxunea

- closed #90 

## 📝 Work Description

-위니 피드, 마이 피드의 전반적인 코드 리팩토링을 진행
- Flow 적용

## 📣 To Reviewers

- 커밋한 리팩토링만 봐주면 감사하겠습니당
- Paging+Loading Indicator 작업하면 코드의 많은 부분에 변동예정이라 [이슈](https://github.com/team-winey/Winey-AOS/issues/90)에 적어둔 리팩토링 사항 빼고는 건드리지 않았어요! 구현 완료하면 마이피드도 같이 최종 리팩토링해서 같이 PR 올리겠습니다

2023-08-04 08:58 UTC, Sangwook123 approved these changes
백혜선 폼 미쳐따이

2023-08-04 08:58 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +        viewModel.getWineyFeedListState.flowWithLifecycle(lifecycle).onEach { state ->
이런 방식도 있군요 ! ! flow를 처리하는 방식은 여러가지가 있는 것 같습니다. flow를 처리하는 함수별 기능적 차이를 좀 더 깊게 공부해보고싶네요 ! !

2023-08-04 08:58 UTC, Sangwook123 commented on app/build.gradle.kts
> +        implementation(swipeRefreshLayout)
오... 당겨서 새로고침 생각보다 편하게 구현이 가능하네요 !!

2023-08-04 08:58 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
> +class WineyFeedDeleteDialogFragment(private val feedId: Int, private val userLevel: Int) :
LOW와 HIGH를 하나로 합친 지금 방식이 훨씬 좋아보입니다 !! 굿굿

2023-08-04 08:58 UTC, Sangwook123 commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +            binding.layoutWineyfeedRefresh.isRefreshing = false
👍👍👍👍

2023-08-05 07:26 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedFragment.kt
> +        viewModel.getWineyFeedListState.flowWithLifecycle(lifecycle).onEach { state ->
collect로 flow를 구독하는 경우 생명주기 처리를 별도로 구독해야하는데, launchIn과 함께 flowWithLifeCycle을 사용하면 생명주기의 변화에 따라 자동으로 처리된다는 장점이 있어서 해당 방법을 사용했습니다 😄

2023-08-05 08:16 UTC, leeeha requested changes
아낌없이 리뷰 달았습니다!! 

리뷰 빨리 달고 싶었는데 Flow에 대해 더 자세히 알수록 질 높은 리뷰를 달 수 있을 거 같아서 시간이 꽤나 걸렸습니닷,,, 기다려줘서 고마워용!! 🥰

2023-08-05 08:16 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
>          } else {
early return 하면 else문은 작성하지 않아도 될 거 같네요!

2023-08-05 08:16 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedViewModel.kt
>          }
와우~~ 제네릭으로 만들어서 사용하니까 중복되는 코드가 확 줄었네요! 🤩

2023-08-05 08:16 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
>          }
이게 리팩토링의 힘인가..!! 👍👍

2023-08-05 08:16 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
>              notifyItemChanged(index)
ListAdapter를 사용하고 있는데 submitList 대신 notifyItemChanged 함수를 사용한 이유가 있을까요??

2023-08-05 08:16 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedDeleteDialogFragment.kt
> +            if (userLevel <= 2) {
요기도 상수화 시켜주는 센스 >.~

2023-08-05 08:16 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
>              }
뷰홀더에서는 fragmentManager 가 사용되지 않는 거 같은데 인자로 넣어준 이유가 있을까요??

2023-08-05 08:30 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
>      }
오 scope 부분 사실 맘대로 아무거나 써왔는데 덕분에 확실히 알고갑니다 고마워용 !

2023-08-05 08:32 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
>          wineyFeedFragment = WineyFeedFragment()
아 함수를 분리하는 과정에서 해당 코드를 안지웠네요 같이 수정하겠습니다:)

2023-08-05 09:05 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
>              notifyItemChanged(index)
헉 왜 저렇게썼지 수정할게요 😲

2023-08-05 09:11 UTC, sxunea commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/mypage/myfeed/MyFeedAdapter.kt
>              }
아 저부분 마이피드 리팩토링할때 같이 추가하려고했어용 페이징 적용할때 ! 잠시만 기다려주길 . .

2023-08-05 09:53 UTC, leeeha requested changes

2023-08-05 09:53 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
>      }
저도 헷갈려서 다시 알아봤는데 위에 링크 걸어둔 스택오버플로우는 LifecycleOwner에 관한 이야기고, 그것과 별개로 지금과 같이 뷰가 있는 다이얼로그 프래그먼트에서는 

```
wineyFeedViewModel.deleteMyFeedState.flowWithLifecycle(viewLifeCycle).onEach { state ->
...
}.launchIn(viewLifeCycleScope)
```

이렇게 viewLifeCycle, viewLifeCycleScope 를 사용하는 게 맞는 거 같아요! 아래 포포리 레포에서도 그렇게 사용했더라구요! 

[이 링크](https://hongbeomi.medium.com/%EB%B2%88%EC%97%AD-android-ui%EC%97%90%EC%84%9C-flow%EB%A5%BC-%EC%88%98%EC%A7%91%ED%95%98%EB%8A%94-%EC%95%88%EC%A0%84%ED%95%9C-%EA%B8%B8-bd8449e67ec3)에도 다음과 같은 설명이 나옵니다. 

<img width="550" src="https://github.com/team-winey/Winey-AOS/assets/68090939/6c1fd646-c1b5-457c-ad7a-8e60aa1aa530"/>

2023-08-05 10:18 UTC, leeeha approved these changes

2023-08-05 10:18 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
>      }
가끔 onCreateDialog에서 초기화 작업을 진행하고 onCreateView 는 사용하지 않는 
다시 말해, 뷰가 없는 DialogFragment에서는 lifeCycleOwner를 사용할 수 있다고 합니다! 

>onAttach
onCreate
onCreateDialog
onCreateView
onActivityCreated
onStart
onResume
>
>onPause
onStop
onDestroyView
onDestroy
onDetach

지금은 뷰가 있는 다이얼로그 프래그먼트니까 view lifecycle/scope 사용하는 게 맞아요! 

cf) https://hongbeomi.medium.com/%EB%B2%88%EC%97%AD-android-ui%EC%97%90%EC%84%9C-flow%EB%A5%BC-%EC%88%98%EC%A7%91%ED%95%98%EB%8A%94-%EC%95%88%EC%A0%84%ED%95%9C-%EA%B8%B8-bd8449e67ec3

2023-08-05 10:24 UTC, sxunea commented
기록용 : [lifecycle vs viewlifecycle](https://velog.io/@jeongminji4490/Android-LifecycleOwner-vs-viewLifecycleOwner-in-Fragment)

2023-08-05 10:25 UTC, leeeha commented on app/src/main/java/com/android/go/sopt/winey/presentation/main/feed/WineyFeedDeleteDialogFragment.kt
>      }
- 액티비티, 뷰가 없는 다이얼로그 프래그먼트: lifecycle, lifecycleScope 
- 프래그먼트, 뷰가 있는 다이얼로그 프래그먼트: viewLifeCycle, viewLifeCycleScope

2023-08-05 10:37 UTC, merged